<footer id="l-footer" class="l-footer">
	<div class="l-footer__wrapper">
		<nav class="nav-contentinfo">
			<ul>
				<li><a href="★★★">★★★</a></li>
				<li><a href="★★★">★★★</a></li>
				<li><a href="★★★">★★★</a></li>
			</ul>
		</nav>
		<p class="txt-copyright"><small>&copy; ★★★, Ltd. All Rights Reserved.</small></p>
	</div>
</footer>
<p class="nav-backtotop"><a href="#l-document">このページの先頭へ戻る</a></p>
